import { writeFile } from 'fs/promises';
import { InsightData } from '../analysis/insights.js';

const CATEGORY_COLORS: Record<string, string> = {
  'Engagement Shifts': '#0891b2',
  'Coverage Opportunities': '#16a34a',
  'Audience Risks': '#dc2626',
  'Revenue Signals': '#ca8a04',
  'Geographic Intelligence': '#9333ea',
};

const CONFIDENCE_COLORS: Record<string, { bg: string; text: string }> = {
  high: { bg: '#16a34a', text: '#ffffff' },
  medium: { bg: '#ca8a04', text: '#ffffff' },
  low: { bg: '#dc2626', text: '#ffffff' },
};

export function generateEmailHTML(insights: InsightData): string {
  const m = insights.topLineMetrics;

  const sectionsHtml = insights.sections.map(section => {
    const color = CATEGORY_COLORS[section.category] || '#6b7280';
    const insightsHtml = section.insights.map(insight => {
      const conf = CONFIDENCE_COLORS[insight.confidence] || CONFIDENCE_COLORS.medium;
      const dataPointsHtml = insight.dataPoints.length > 0
        ? `<p style="font-size:13px;color:#9ca3af;margin:8px 0 0 0;">Data: ${insight.dataPoints.join(' &bull; ')}</p>`
        : '';
      return `
        <div style="background:#f9fafb;border-radius:8px;padding:16px;margin:12px 0;">
          <div style="margin-bottom:8px;">
            <span style="display:inline-block;background:${conf.bg};color:${conf.text};font-size:11px;font-weight:700;padding:2px 8px;border-radius:4px;text-transform:uppercase;margin-right:8px;">${insight.confidence}</span>
            <strong style="font-size:16px;color:#111827;">${insight.headline}</strong>
          </div>
          <p style="color:#374151;font-size:14px;line-height:1.6;margin:8px 0;">${insight.detail}</p>
          <p style="color:#111827;font-size:14px;margin:8px 0;"><strong>&rarr;</strong> <em>${insight.action}</em></p>
          ${dataPointsHtml}
        </div>`;
    }).join('');

    return `
      <div style="margin:32px 0;">
        <h2 style="color:${color};font-size:18px;border-bottom:2px solid ${color};padding-bottom:8px;margin-bottom:16px;">
          &#9632; ${section.category}
        </h2>
        ${insightsHtml}
      </div>`;
  }).join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Newsroom Radar Briefing — ${insights.briefingDate}</title>
</head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:640px;margin:0 auto;background:#ffffff;border-radius:12px;overflow:hidden;margin-top:24px;margin-bottom:24px;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

    <div style="background:linear-gradient(135deg,#1e3a5f,#2563eb);padding:32px;text-align:center;">
      <h1 style="color:#ffffff;font-size:24px;margin:0;">Newsroom Radar</h1>
      <p style="color:#93c5fd;font-size:14px;margin:8px 0 0 0;">Audience Intelligence Briefing • ${insights.briefingDate}</p>
    </div>

    <div style="padding:24px;">
      <div style="display:flex;justify-content:space-around;text-align:center;background:#f0f9ff;border-radius:8px;padding:16px;margin-bottom:24px;">
        <div style="display:inline-block;text-align:center;padding:0 16px;">
          <div style="font-size:28px;font-weight:700;color:#1e3a5f;">${m.totalReaders}</div>
          <div style="font-size:12px;color:#6b7280;">Total Readers</div>
        </div>
        <div style="display:inline-block;text-align:center;padding:0 16px;">
          <div style="font-size:28px;font-weight:700;color:#16a34a;">${m.highEngagement}</div>
          <div style="font-size:12px;color:#6b7280;">Highly Engaged</div>
        </div>
        <div style="display:inline-block;text-align:center;padding:0 16px;">
          <div style="font-size:28px;font-weight:700;color:#dc2626;">${m.atRiskReaders}</div>
          <div style="font-size:12px;color:#6b7280;">At Risk</div>
        </div>
        <div style="display:inline-block;text-align:center;padding:0 16px;">
          <div style="font-size:28px;font-weight:700;color:#ca8a04;">${m.totalDonors}</div>
          <div style="font-size:12px;color:#6b7280;">Donors</div>
        </div>
      </div>

      <p style="color:#6b7280;font-size:13px;text-align:center;">Top topics: ${m.topTopics.join(' • ')}</p>
      <p style="color:#6b7280;font-size:13px;text-align:center;margin-bottom:8px;">${insights.totalAudienceAnalyzed} audience members analyzed</p>

      ${sectionsHtml}
    </div>

    <div style="background:#f9fafb;padding:16px;text-align:center;border-top:1px solid #e5e7eb;">
      <p style="color:#9ca3af;font-size:12px;margin:0;">Generated by Newsroom Radar — AI-powered audience intelligence for local newsrooms</p>
    </div>
  </div>
</body>
</html>`;
}

export async function saveEmailReport(insights: InsightData, outputPath: string): Promise<void> {
  const html = generateEmailHTML(insights);
  await writeFile(outputPath, html, 'utf-8');
}
