import chalk from 'chalk';
import { InsightData } from '../analysis/insights.js';

const CATEGORY_COLORS: Record<string, (s: string) => string> = {
  'Engagement Shifts': chalk.cyan,
  'Coverage Opportunities': chalk.green,
  'Audience Risks': chalk.red,
  'Revenue Signals': chalk.yellow,
  'Geographic Intelligence': chalk.magenta,
};

const CONFIDENCE_BADGE: Record<string, string> = {
  high: chalk.bgGreen.black(' HIGH '),
  medium: chalk.bgYellow.black(' MED '),
  low: chalk.bgRed.white(' LOW '),
};

export function renderTerminalReport(insights: InsightData): void {
  const width = Math.min(process.stdout.columns || 80, 100);
  const line = chalk.dim('─'.repeat(width));
  const doubleLine = chalk.bold('═'.repeat(width));

  console.log('\n' + doubleLine);
  console.log(chalk.bold.white('  NEWSROOM RADAR — Audience Intelligence Briefing'));
  console.log(chalk.dim(`  ${insights.briefingDate} • ${insights.totalAudienceAnalyzed} audience members analyzed`));
  console.log(doubleLine);

  // Top-line metrics
  const m = insights.topLineMetrics;
  console.log('\n' + chalk.bold('  TOP-LINE METRICS'));
  console.log(line);
  console.log(
    `  ${chalk.bold.white(String(m.totalReaders))} readers  •  ` +
    `${chalk.bold.green(String(m.highEngagement))} highly engaged  •  ` +
    `${chalk.bold.red(String(m.atRiskReaders))} at risk  •  ` +
    `${chalk.bold.yellow(String(m.totalDonors))} donors`
  );
  console.log(`  ${chalk.dim('Top topics:')} ${m.topTopics.map(t => chalk.cyan(t)).join(', ')}`);
  console.log('');

  // Sections
  for (const section of insights.sections) {
    const colorFn = CATEGORY_COLORS[section.category] || chalk.white;
    console.log(line);
    console.log(`\n  ${colorFn(chalk.bold(`■ ${section.category.toUpperCase()}`))}`);
    console.log('');

    for (const insight of section.insights) {
      const badge = CONFIDENCE_BADGE[insight.confidence] || '';
      console.log(`  ${badge} ${chalk.bold.white(insight.headline)}`);
      console.log('');
      console.log(wrapText(insight.detail, width - 4, '    '));
      console.log('');
      console.log(`    ${chalk.bold('→')} ${chalk.italic(insight.action)}`);
      if (insight.dataPoints.length > 0) {
        console.log(chalk.dim(`    Data: ${insight.dataPoints.join(' | ')}`));
      }
      console.log('');
    }
  }

  console.log(doubleLine);
  console.log(chalk.dim('  Generated by Newsroom Radar • newsroom-radar.org'));
  console.log(doubleLine + '\n');
}

function wrapText(text: string, maxWidth: number, indent: string): string {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = indent;

  for (const word of words) {
    if (currentLine.length + word.length + 1 > maxWidth) {
      lines.push(currentLine);
      currentLine = indent + word;
    } else {
      currentLine += (currentLine === indent ? '' : ' ') + word;
    }
  }
  if (currentLine.trim()) lines.push(currentLine);
  return lines.join('\n');
}
