import chalk from 'chalk';
import { InsightData } from '../analysis/insights.js';
import { MetricsSummary } from '../analysis/metrics.js';

const CATEGORY_COLORS: Record<string, (s: string) => string> = {
  'Engagement Shifts': chalk.cyan,
  'Coverage Opportunities': chalk.green,
  'Audience Risks': chalk.red,
  'Revenue Signals': chalk.yellow,
  'Geographic Intelligence': chalk.magenta,
};

const CONFIDENCE_BADGE: Record<string, string> = {
  high: chalk.bgGreen.black(' HIGH '),
  medium: chalk.bgYellow.black(' MED '),
  low: chalk.bgRed.white(' LOW '),
};

export function renderTerminalReport(insights: InsightData, metrics?: MetricsSummary): void {
  const width = Math.min(process.stdout.columns || 80, 100);
  const line = chalk.dim('─'.repeat(width));
  const doubleLine = chalk.bold('═'.repeat(width));

  console.log('\n' + doubleLine);
  console.log(chalk.bold.white('  NEWSROOM RADAR — Audience Intelligence Briefing'));
  console.log(chalk.dim(`  ${insights.briefingDate} • ${insights.totalAudienceAnalyzed} audience members analyzed`));
  console.log(doubleLine);

  // Top-line metrics
  const m = insights.topLineMetrics;
  console.log('\n' + chalk.bold('  TOP-LINE METRICS'));
  console.log(line);
  console.log(
    `  ${chalk.bold.white(String(m.totalReaders))} readers  •  ` +
    `${chalk.bold.green(String(m.highEngagement))} highly engaged  •  ` +
    `${chalk.bold.red(String(m.atRiskReaders))} at risk  •  ` +
    `${chalk.bold.yellow(String(m.totalDonors))} donors`
  );
  console.log(`  ${chalk.dim('Top topics:')} ${m.topTopics.map(t => chalk.cyan(t)).join(', ')}`);
  console.log('');

  // Data summary — computed metrics
  if (metrics) {
    renderDataSummary(metrics, width, line);
  }

  // AI Insight sections
  console.log(line);
  console.log(`\n  ${chalk.bold.white('AI-SYNTHESIZED INSIGHTS')}`);
  console.log(chalk.dim('  The following insights were generated by analyzing the metrics above.\n'));

  for (const section of insights.sections) {
    const colorFn = CATEGORY_COLORS[section.category] || chalk.white;
    console.log(line);
    console.log(`\n  ${colorFn(chalk.bold(`■ ${section.category.toUpperCase()}`))}`);
    console.log('');

    for (const insight of section.insights) {
      const badge = CONFIDENCE_BADGE[insight.confidence] || '';
      console.log(`  ${badge} ${chalk.bold.white(insight.headline)}`);
      console.log('');
      console.log(wrapText(insight.detail, width - 4, '    '));
      console.log('');
      console.log(`    ${chalk.bold('→')} ${chalk.italic(insight.action)}`);
      if (insight.dataPoints.length > 0) {
        console.log(chalk.dim(`    Data: ${insight.dataPoints.join(' | ')}`));
      }
      console.log('');
    }
  }

  console.log(doubleLine);
  console.log(chalk.dim('  Generated by Newsroom Radar • newsroom-radar.org'));
  console.log(doubleLine + '\n');
}

function renderDataSummary(m: MetricsSummary, width: number, line: string): void {
  console.log(line);
  console.log(`\n  ${chalk.bold.white('COMPUTED DATA SUMMARY')}`);
  console.log(chalk.dim(`  Engagement period: ${m.overview.engagementPeriod}`));
  console.log(chalk.dim(`  Data sources: ${m.overview.dataSources.join(', ')}\n`));

  // Engagement histogram
  console.log(chalk.bold('  Engagement Distribution (current vs. previous)'));
  for (let i = 1; i <= 5; i++) {
    const curr = m.engagementDistribution.current[String(i)] || 0;
    const prev = m.engagementDistribution.previous[String(i)] || 0;
    const bar = chalk.green('█'.repeat(Math.round(curr / 5)));
    const delta = curr - prev;
    const deltaStr = delta > 0 ? chalk.green(`+${delta}`) : delta < 0 ? chalk.red(`${delta}`) : chalk.dim('±0');
    console.log(`    Score ${i}: ${bar} ${curr} (was ${prev}, ${deltaStr})`);
  }
  console.log('');

  // Engagement changes
  const ec = m.engagementChanges;
  console.log(chalk.bold('  Engagement Changes'));
  console.log(`    ${chalk.green(`↑ ${ec.jumpedCount} readers`)} jumped significantly (2+ points or crossed into high)`);
  console.log(`    ${chalk.red(`↓ ${ec.declinedCount} readers`)} declined significantly`);
  console.log(`    ${chalk.dim(`— ${ec.stableCount} readers`)} stable`);
  console.log('');

  // Top content by jumpers
  if (m.cohortAnalysis.engagementJumpersByContent.length > 0) {
    console.log(chalk.bold('  Content That Drove Engagement Jumps'));
    for (const item of m.cohortAnalysis.engagementJumpersByContent.slice(0, 5)) {
      const donorNote = item.newDonorCount > 0 ? chalk.yellow(` (${item.newDonorCount} became donors)`) : '';
      console.log(`    ${item.contentTopic}: ${chalk.white(String(item.jumperCount))} jumpers${donorNote}`);
    }
    console.log('');
  }

  // Churn clusters
  if (m.cohortAnalysis.churnClusters.length > 0) {
    console.log(chalk.bold('  Churn Clusters (3+ declining readers in same ZIP)'));
    for (const cluster of m.cohortAnalysis.churnClusters.slice(0, 5)) {
      console.log(`    ZIP ${cluster.postalCode}: ${chalk.red(String(cluster.count))} readers (${cluster.avgPreviousScore} → ${cluster.avgCurrentScore})`);
      console.log(chalk.dim(`      Shared topics: ${cluster.sharedTopics.join(', ')}`));
    }
    console.log('');
  }

  // Top 5 content
  console.log(chalk.bold('  Top Content by Views'));
  for (const item of m.contentPerformance.slice(0, 5)) {
    console.log(`    ${chalk.white(String(item.totalViews).padStart(3))} views  ${item.avgTimeMinutes}min avg  ${Math.round(item.avgCompletionRate * 100)}% completion  ${chalk.dim(item.title)}`);
  }
  console.log('');

  // Geographic highlights
  console.log(chalk.bold('  Geographic Highlights'));
  for (const geo of m.geographicBreakdown.slice(0, 5)) {
    const donorRate = geo.readerCount > 0 ? Math.round((geo.donors / geo.readerCount) * 100) : 0;
    const matchLabel = geo.contentMatchScore < 60 ? chalk.red(`${geo.contentMatchScore}% content match`) : chalk.green(`${geo.contentMatchScore}% content match`);
    console.log(`    ZIP ${geo.postalCode}: ${geo.readerCount} readers, avg ${geo.avgEngagement}, ${geo.donors} donors (${donorRate}%), ${matchLabel}`);
  }
  console.log('');

  // Donor funnel
  console.log(chalk.bold('  Donor Funnel'));
  console.log(`    Non-donors: ${m.donorFunnel.nonDonors} | Minor donors: ${m.donorFunnel.minorDonors} | Major donors: ${m.donorFunnel.majorDonors}`);
  console.log(`    ${chalk.green(`${m.donorFunnel.newDonors} new donors`)} this period | ${chalk.yellow(`${m.donorFunnel.highEngagementNonDonors} high-engagement non-donors`)} (conversion pipeline)`);
  if (m.donorFunnel.contentBeforeDonation.length > 0) {
    console.log(chalk.dim('    Top content read before first donation:'));
    for (const c of m.donorFunnel.contentBeforeDonation.slice(0, 3)) {
      console.log(chalk.dim(`      ${c.donorCount} donors read: ${c.articleTitle}`));
    }
  }
  console.log('');

  // Survey summary
  if (m.surveyHighlights.totalResponses > 0) {
    console.log(chalk.bold(`  Survey Highlights (${m.surveyHighlights.totalResponses} responses)`));
    for (const q of m.surveyHighlights.byQuestion) {
      if (q.topThemes.length > 0) {
        const themes = q.topThemes.slice(0, 3).map(t => `${t.theme} (${t.count})`).join(', ');
        console.log(`    "${q.question}"`);
        console.log(chalk.dim(`      Top themes: ${themes}`));
      }
    }
    console.log('');
  }
}

function wrapText(text: string, maxWidth: number, indent: string): string {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = indent;

  for (const word of words) {
    if (currentLine.length + word.length + 1 > maxWidth) {
      lines.push(currentLine);
      currentLine = indent + word;
    } else {
      currentLine += (currentLine === indent ? '' : ' ') + word;
    }
  }
  if (currentLine.trim()) lines.push(currentLine);
  return lines.join('\n');
}
